"""empty message

Revision ID: 10558e72b809
Revises: 30fc1b283a4a
Create Date: 2019-05-04 14:58:58.122671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10558e72b809'
down_revision = '30fc1b283a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_img', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploadimage')
    # ### end Alembic commands ###
