"""empty message

Revision ID: 20772dca9e5a
Revises: 9017e44b9ea8
Create Date: 2019-04-23 19:07:50.884938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20772dca9e5a'
down_revision = '9017e44b9ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogposts', 'header_img',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogposts', 'header_img',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
