"""empty message

Revision ID: 851906bbe1e0
Revises: 20772dca9e5a
Create Date: 2019-04-23 20:36:08.766633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851906bbe1e0'
down_revision = '20772dca9e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'header_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('header_img', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
